### ISSUE TITLE
SVG mixin not working

### ISSUE THREAD

**Issue by MilindB05** [matthew-dean/Crunch#113]
Hi,

This mixin used for SVG background fills as mentioned in the link below, doesn't work in the crunch compiler. The SVG path does not convert into the data URI when the less is compiled using Crunch. Neither does the @fill-default and @fill-new variables work as desired.
MIXIN:
.icon-fill(@src, @fill-default, @fill-new) {
    @escape-fill-default: escape(@fill-default);
    @escape-fill-new: escape(@fill-new);
    @data-uri: data-uri('image/svg+xml;charset=UTF-8',"@{src}");
    @replace-src: replace("@{data-uri}","@{escape-fill-default}","@{escape-fill-new}");
    background-image: e(@replace-src);
}
Details:  http://zslabs.com/articles/svg-background-fill

Thanks,
Milind

**Comment by matthew-dean** [comment]
Reposted from the comments on that page: 

Currently, Crunch uses the "browser" mode of Less, which doesn't support data-uris, and instead returns a url(), which would still be just a reference to that file. So the Less compiler is still "native", but the browser version supports a slightly reduced version of the Node version. Therefore, the replace function in this example wouldn't work. Sorry about that.

For version 2 of Crunch (in development), it will consume the Node.js version of and give an identical output to using lessc, and this won't be a problem.

One workaround would be defining your SVG file as a string inline in a .less file, rather than referencing the file. Then you could do all the string replacements in the example.

**Comment by MilindB05** [comment]
Sounds good :)...I will definitely try using the SVG as a string as siggested by you. Thanks a lot :)
- Milind
