### ISSUE TITLE
Using Javascript in Crunch

### ISSUE THREAD

**Issue by Pantyboy** [matthew-dean/Crunch#119]
Hello again

I don't know if this is a "me" or "you" issue, so I decided to ask the experts.

I understand that I can use Javascript in Less. The code I'm trying is "@winHeight:`$(window).$(height)`;" but Crunch gives me a compiler error "You are using JavaScript, which has been disabled." which I presumed was the backticks which I believe you have to use if you use Javascript in Less.

When I remove the backticks, the file compiles.

Please forgive me but I thought I'd check if it was a Crunch thing first as I have no idea what it is I'm doing,

Martin

**Comment by matthew-dean** [comment]
The practical reason for JavaScript being switched off is that it simply wouldn't work in Crunch 1.x. Adobe AIR does not allow eval statements, end of story (as a security precaution, although a little overbearing).

Even if it did, your example doesn't make sense. Because there's no accessible window object, other than the app window, so you'd basically be measuring the height of the Crunch window.

JavaScript really only makes sense if you use Less in the browser, which the Less team doesn't recommend. Some Less libraries use it to inject functionality, but it's more of a language hack.

Personally, I'm not a fan of injecting another language into a CSS-like syntax, so that's why I (and others) pushed hard for Less to support an official plugin syntax, which it now does.

Crunch 2.x has the capability of supporting JavaScript (since it's no longer Adobe AIR), but I'm on the fence about supporting it for those other reasons. At the least, it won't be enabled by default, but there would be a way to enable it via editing a config file.

**Comment by Pantyboy** [comment]
Hi Matt

Thanks for the reply and the (excellent) explanation.

I'm trying to find a(n easy) way to find the height of the browser window so I can use a percentage for a specific <div>.

I found the example on 'Stackoverflow' where there was a question regarding finding the browser height in LESS.

However, if you and the LESS team don't recommend doing it this way then that's good enough for me. I'll take another look at the LESS website regarding the plugin.

Once again, many thanks for your reply and your patience.

Martin

**Comment by matthew-dean** [comment]
All Less config options are available in Crunch 2.
