### ISSUE TITLE
Syntax Highlighter Colour Options and Compiler Errors issues

### ISSUE THREAD

**Issue by anguswf** [matthew-dean/Crunch#123]
Hi Matthew, I'm finding on high res screens its very hard to see the periods "." . This often leads to some frustrations! Is there a way the periods could be darker somehow or could there be a button to highlight them. 

The compiler errors window does not report errors accurately. The line numbers are incorrect as is the file where the error occurs, especially if inside mixins and where you have "included" files to be crunched. Working on many includes such as bootstrap + theme less files  this can be a real drag trying to track back through to locate the error.

Many Thanks Angus

**Comment by matthew-dean** [comment]
I'm close to releasing Crunch 2, so development on Crunch 1 has stopped. Crunch 2 has more accurate error tracking (supported by a newer Less version), and also allows you to click to the line of the error to the relevant line of the import.

Fonts should also look better now, with rendering on Chromium rather than Adobe AIR. So this should address the difficulty you're seeing with the periods.

You can try the latest beta: https://github.com/Crunch/Crunch-2/releases

I'm hoping to release another beta in the next day or so.

**Comment by anguswf** [comment]
Thats great news. Hopefully it run faster as well :) Thanks for the effort you guys are putting in.
