### ISSUE TITLE
LESS beautify?

### ISSUE THREAD

**Issue by MaureenD** [matthew-dean/Crunch#58]
Has anyone requested a feature for next release to add a code formatting or beautifier command for the LESS files? Or does it already exist and I haven't figure it out yet?

**Comment by matthew-dean** [comment]
If there's a less beautifier that already exists in JavaScript, we could consider it, and I plan to put in some better options for managing large projects between multiple .less users (and maintaining good whitespace settings), so closing this issue as beatification itself seems off the implementation list at the moment.

**Comment by joeyhub** [comment]
I suppose what we're really asking for is a proper grammar to be able to build an AST, etc.

**Comment by matthew-dean** [comment]
Then this is not a Crunch question, this is a Less question. Crunch doesn't define the way the AST is constructed for Less, nor the options for output. 

Since Less 2.0, Less allows pre-loaded plugins that can alter the grammar of input, and change the format of output. The next major version of Crunch will support adding Less plugins.

See http://lesscss.org/usage/#plugins for more info about plugins.
